services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST
    labels:
      com.vibehost.role: FRONTEND
      com.vibehost.route: both
      com.vibehost.app-port: "3000"
